/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analysis/agreement/{country}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agreement */
        get: operations["agreement_api_v1_analysis_agreement__country__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/multilateral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Multilateral */
        get: operations["multilateral_api_v1_analysis_multilateral_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/subjects/{country}/{comparison}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Subjects */
        get: operations["subjects_api_v1_analysis_subjects__country___comparison__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/timeline/{country}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline
         * @description Full-history session means. Date/subject filters intentionally do not apply.
         */
        get: operations["timeline_api_v1_analysis_timeline__country__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/words/{mode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Words */
        get: operations["words_api_v1_analysis_words__mode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries/{country}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_v1_countries__country__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata */
        get: operations["metadata_api_v1_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Methodology */
        get: operations["methodology_api_v1_methodology_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolutions */
        get: operations["resolutions_api_v1_resolutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolutions/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Resolutions */
        get: operations["export_resolutions_api_v1_resolutions_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolutions/{resolution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolution Detail */
        get: operations["resolution_detail_api_v1_resolutions__resolution_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgreementResult */
        AgreementResult: {
            /** Consensus Midpoint */
            consensus_midpoint: number | null;
            /** Country */
            country: string;
            /** Items */
            items: components["schemas"]["AgreementRow"][];
            /** Reference Longitude */
            reference_longitude: number;
            /** Resolution Count */
            resolution_count: number;
        };
        /** AgreementRow */
        AgreementRow: {
            /** Country */
            country: string;
            /** Score */
            score: number | null;
            /** Shared Votes */
            shared_votes: number;
        };
        /** Country */
        Country: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** M49 */
            m49: string | null;
            /** Membership End */
            membership_end: string | null;
            /** Membership Start */
            membership_start: string | null;
            /** Name */
            name: string;
            /** Region */
            region: string;
            /** Search Terms */
            search_terms: string;
            /** Subregion */
            subregion: string | null;
        };
        /** CountryPreset */
        CountryPreset: {
            /** Countries */
            countries: string[];
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** Era */
        Era: {
            /** End */
            end: number | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Start */
            start: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Metadata */
        Metadata: {
            /** Countries */
            countries: components["schemas"]["Country"][];
            /** Country Presets */
            country_presets: components["schemas"]["CountryPreset"][];
            /** Dataset Version */
            dataset_version: string;
            /** Earliest Date */
            earliest_date: string | null;
            /** Eras */
            eras: components["schemas"]["Era"][];
            /** Languages */
            languages: string[];
            /** Latest Date */
            latest_date: string | null;
            /** Subjects */
            subjects: components["schemas"]["Subject"][];
            /** Word Modes */
            word_modes: string[];
        };
        /** Methodology */
        Methodology: {
            /** Definitions */
            definitions: {
                [key: string]: string;
            };
            /** Formula */
            formula: string;
            /** Limitations */
            limitations: string[];
            /** Scope */
            scope: string;
            /** Sources */
            sources: string[];
            /** Thresholds */
            thresholds: {
                [key: string]: number;
            };
            /** Version */
            version: string;
            /** Vote Encoding */
            vote_encoding: {
                [key: string]: number;
            };
        };
        /** MultilateralResult */
        MultilateralResult: {
            /** Items */
            items: components["schemas"]["MultilateralRow"][];
            /** Mean Alignment */
            mean_alignment: number | null;
            /** Minimum Votes */
            minimum_votes: number;
            /** Resolution Count */
            resolution_count: number;
        };
        /** MultilateralRow */
        MultilateralRow: {
            /** Abstention Rate */
            abstention_rate: number | null;
            /** Country */
            country: string;
            /** Multilateral Alignment */
            multilateral_alignment: number | null;
            /** No Rate */
            no_rate: number | null;
            /** Participation Count */
            participation_count: number;
            /** Yes Rate */
            yes_rate: number | null;
        };
        /** Overview */
        Overview: {
            /** Countries */
            countries: number;
            /** Earliest Date */
            earliest_date: string | null;
            /** Latest Date */
            latest_date: string | null;
            /** Recent */
            recent: components["schemas"]["Resolution"][];
            /** Resolutions */
            resolutions: number;
            /** Subject Links */
            subject_links: number;
            /** Subjects */
            subjects: number;
            votes: components["schemas"]["VoteCounts"];
        };
        /** Profile */
        Profile: {
            /** Alignment */
            alignment: number | null;
            country: components["schemas"]["Country"];
            /** End Date */
            end_date: string | null;
            /** Least Aligned */
            least_aligned: components["schemas"]["AgreementRow"][];
            /** Minimum Shared Votes */
            minimum_shared_votes: number;
            /** Most Aligned */
            most_aligned: components["schemas"]["AgreementRow"][];
            /** Opposed High Consensus */
            opposed_high_consensus: components["schemas"]["Resolution"][];
            /** Rank */
            rank: number | null;
            /** Ranked Countries */
            ranked_countries: number;
            /** Resolution Count */
            resolution_count: number;
            /** Start Date */
            start_date: string | null;
            /** Supported Low Consensus */
            supported_low_consensus: components["schemas"]["Resolution"][];
            votes: components["schemas"]["VoteCounts"];
            /** Yearly */
            yearly: components["schemas"]["YearPoint"][];
        };
        /** Resolution */
        Resolution: {
            /** Consensus */
            consensus: number | null;
            counts: components["schemas"]["VoteCounts"];
            /** Date */
            date: string | null;
            /** Id */
            id: string;
            /** Session */
            session: string | null;
            /** Source Url */
            source_url: string | null;
            /** Symbol */
            symbol: string | null;
            /** Title */
            title: string;
            /** Votes */
            votes: {
                [key: string]: ("Y" | "N" | "A" | "X") | null;
            };
        };
        /** ResolutionDetail */
        ResolutionDetail: {
            /** Consensus */
            consensus: number | null;
            counts: components["schemas"]["VoteCounts"];
            /** Date */
            date: string | null;
            /** Id */
            id: string;
            /** Session */
            session: string | null;
            /** Source Url */
            source_url: string | null;
            /** Subjects */
            subjects: components["schemas"]["Subject"][];
            /** Symbol */
            symbol: string | null;
            /** Title */
            title: string;
            /** Votes */
            votes: {
                [key: string]: ("Y" | "N" | "A" | "X") | null;
            };
        };
        /** ResolutionPage */
        ResolutionPage: {
            /** Items */
            items: components["schemas"]["Resolution"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Subject */
        Subject: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Parents */
            parents: string[];
            /** Top Level */
            top_level: boolean;
        };
        /** SubjectResult */
        SubjectResult: {
            /** Comparison */
            comparison: string;
            /** Country */
            country: string;
            /** Items */
            items: components["schemas"]["SubjectScore"][];
            /** Minimum Shared Votes */
            minimum_shared_votes: number;
        };
        /** SubjectScore */
        SubjectScore: {
            /** Score */
            score: number;
            /** Shared Votes */
            shared_votes: number;
            /** Subject Id */
            subject_id: string;
            /** Subject Label */
            subject_label: string;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Scores */
            scores: {
                [key: string]: number | null;
            };
            /** Session */
            session: string;
            /** Shared Votes */
            shared_votes: {
                [key: string]: number;
            };
            /** Special */
            special: boolean;
            /** Year */
            year: number | null;
        };
        /** TimelineResult */
        TimelineResult: {
            /** Comparisons */
            comparisons: string[];
            /** Country */
            country: string;
            /** Items */
            items: components["schemas"]["TimelinePoint"][];
            /** Minimum Shared Votes */
            minimum_shared_votes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoteCounts */
        VoteCounts: {
            /** Abstain */
            abstain: number | null;
            /** No */
            no: number | null;
            /** Not Voting */
            not_voting: number | null;
            /** Yes */
            yes: number | null;
        };
        /** Word */
        Word: {
            /** Consensus */
            consensus: number | null;
            /** Count */
            count: number;
            /** Subject Ids */
            subject_ids: string[];
            /** Term */
            term: string;
        };
        /** WordResult */
        WordResult: {
            /** Available */
            available: boolean;
            /** Items */
            items: components["schemas"]["Word"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "default" | "geopolitical" | "thematic" | "action" | "category";
            /** Resolution Count */
            resolution_count: number;
        };
        /** YearPoint */
        YearPoint: {
            /** Scores */
            scores: {
                [key: string]: number | null;
            };
            /** Year */
            year: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agreement_api_v1_analysis_agreement__country__get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                subject?: string[];
                include_descendants?: boolean;
                country?: string | null;
                country_mode?: "none" | "voted" | "member";
                keyword?: string;
            };
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    multilateral_api_v1_analysis_multilateral_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                subject?: string[];
                include_descendants?: boolean;
                country?: string | null;
                country_mode?: "none" | "voted" | "member";
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultilateralResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subjects_api_v1_analysis_subjects__country___comparison__get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                parent?: string | null;
            };
            header?: never;
            path: {
                country: string;
                comparison: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_v1_analysis_timeline__country__get: {
        parameters: {
            query?: {
                compare?: string[] | null;
                include_special?: boolean;
            };
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    words_api_v1_analysis_words__mode__get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                subject?: string[];
                include_descendants?: boolean;
                country?: string | null;
                country_mode?: "none" | "voted" | "member";
                keyword?: string;
            };
            header?: never;
            path: {
                mode: "default" | "geopolitical" | "thematic" | "action" | "category";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WordResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_v1_countries__country__profile_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                compare?: string[] | null;
            };
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metadata_api_v1_metadata_get: {
        parameters: {
            query?: {
                language?: "en" | "fr" | "es" | "ar" | "zh" | "ru";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metadata"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    methodology_api_v1_methodology_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Methodology"];
                };
            };
        };
    };
    overview_api_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    resolutions_api_v1_resolutions_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                subject?: string[];
                include_descendants?: boolean;
                country?: string | null;
                country_mode?: "none" | "voted" | "member";
                keyword?: string;
                compare?: string[];
                vote?: ("Y" | "N" | "A" | "X") | null;
                agreement?: ("AGREED" | "DISAGREED" | "STRONGLY_DISAGREED") | null;
                sort?: "date_desc" | "date_asc" | "consensus_desc" | "consensus_asc";
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_resolutions_api_v1_resolutions_export_csv_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                subject?: string[];
                include_descendants?: boolean;
                country?: string | null;
                country_mode?: "none" | "voted" | "member";
                keyword?: string;
                compare?: string[];
                vote?: ("Y" | "N" | "A" | "X") | null;
                agreement?: ("AGREED" | "DISAGREED" | "STRONGLY_DISAGREED") | null;
                sort?: "date_desc" | "date_asc" | "consensus_desc" | "consensus_asc";
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All matching resolutions, using exactly the list's filters and ordering (pagination is ignored). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolution_detail_api_v1_resolutions__resolution_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resolution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
